version: "3.3"

services:
  capture:
    build:
      context: .
    image: richardkdrew/phototimer
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - /var/image:/var/image
      - ./config.py:/root/images/config.py:ro
    restart: unless-stopped
    privileged: true
